name: Markdown quality control

on: [push]

jobs:
  check_links:
    name: Markdown - Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check if Markdown links are valid
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with: 
          config-file: '.github/workflow-templates/markdown-ci/mlc_config.json'
          folder-path: "."

  lint-check:
    name: Markdown - Linting Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check if Markdown is formatted correctly
      uses: avto-dev/markdown-lint@v1
      with:
        config: '.github/workflow-templates/markdown-ci/markdown-config.yml'
        args: '.'
        fix: true
